#!/usr/bin/env bash
set -e

# give sudo permission for ${user} to run yum
echo '${user} ALL=NOPASSWD: /usr/bin/yum' >> /etc/sudoers

curl --create-dirs -fsSLo /usr/share/jenkins/slave.jar \
    https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/${AGENT_VERSION}/remoting-${AGENT_VERSION}.jar

chmod 755 /usr/share/jenkins
chmod 644 /usr/share/jenkins/slave.jar

groupadd -g ${gid} ${group}
useradd --shell /bin/bash -c 'Jenkins user' -G lucky -u ${uid} -g ${gid} -m ${user}

mkdir /home/${user}/.jenkins
mkdir /home/${user}/agent

chown -R ${user}:${group} /home/${user}
