#! /bin/sh -eu

# (centos:6 only) If glibc-common is updated, we have to manually purge non-en_US locales.
if grep -F 'CentOS release 6' /etc/centos-release ; then
    if locale -a | grep nds_DE ; then
        cp /usr/lib/locale/locale-archive /usr/lib/locale/locale-archive.tmpl
        localedef -i en_US -f UTF-8 en_US.UTF-8
        : > /usr/lib/locale/locale-archive.tmpl
    fi
fi
yum clean all
rm -rf /var/cache/yum/*
